### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by cameronmarklewis** [riptidewave93/UNVR-NAS#13]
I've downloaded the UNVR-Pro firmware, size ,name and location are correct. I've made sure all the packages are installed, I then run:

> BOARD=UNVRPRO make

but I immediately get the following:

> sudo modprobe loop; \
sudo modprobe binfmt_misc
Starting 00_prereq_check.sh
Finished 00_prereq_check.sh
Starting 01_pre_docker.sh
Warning: /home/parallels/Desktop/UNVR-NAS-main/BuildEnv/fw-extract/19bf-UNVRPRO-4.0.6-6dd303cb-cb6d-4904-a8ee-ef6e5353016d is not a directory, attempting to create it...
Traceback (most recent call last):
  File "/home/parallels/Desktop/UNVR-NAS-main/scripts/ubnt-fw-parse.py", line 109, in <module>
    main(args.file, args.savedir)
  File "/home/parallels/Desktop/UNVR-NAS-main/scripts/ubnt-fw-parse.py", line 27, in main
    ubntheadercrc = int.from_bytes(mm.read(0x4))  # Read header CRC, convert to int
TypeError: from_bytes() missing required argument 'byteorder' (pos 2)
make: *** [Makefile:9: build] Error 1

**Comment by riptidewave93** [comment]
@cameronmarklewis what version of python are you using? I use 3.12 without issue. I may need to move the python firmware extract tool to a docker command to simplify this

**Comment by riptidewave93** [comment]
@cameronmarklewis this should now be fixed as of commit https://github.com/riptidewave93/UNVR-NAS/commit/d1aaa4bccdf821dc7c56e9d8a31d7add072e1297

**Comment by cameronmarklewis** [comment]
I was using python version 3.10.6. As of your latest commit it's also working for me. Thanks!
