### ISSUE TITLE
Add support for plain Debian or ubuntu

### ISSUE THREAD

**Issue by cainmp** [riptidewave93/UNVR-NAS#14]
Love the idea of this project, but I think it would be better if not coupled to only the Debian + OMV it currently is. Offering either a plain Debian install, or Ubuntu would greatly increase its usefulness IMO.

**Comment by riptidewave93** [comment]
@cainmp you could always install this, and apt remove openmediavault if you want to just use Debian. Compromises were made in this repo due to no GPL source for the kernel; so if you go your own path expect there to be dragons due to a ton of missing kernel modules.

**Comment by cainmp** [comment]
Yeah, every project that has tried to do this has fizzled out due to a lack of kernel support. I have asked a few times for the kernel GPL, which has gone unanswered.

**Comment by riptidewave93** [comment]
Same, and until there's GPL there's no easy way to do your request unless folks want a stripped down system; this is why I targeted OpenMediaVault; the scope was much smaller :) 

Closing this out, but am open to bringing it back once we have Kernel GPL that's not 2+ years old.
