### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by gurudlan** [riptidewave93/UNVR-NAS#15]
Hello, 

i have Unifi Pro OS 4.0.6, when i call command "BOARD=UNVRPRO make" i got error: 

sudo modprobe loop; \
sudo modprobe binfmt_misc
modprobe: FATAL: Module binfmt_misc not found in directory /lib/modules/4.19.152-alpine-unvr
make: *** [Makefile:5: setup] Error 1

Any idea how to fix it and built it?

Thank you

**Comment by riptidewave93** [comment]
Hello @gurudlan,

The error implies your trying to build the firmware ON the NVR itself. You need to do this on a local Linux machine, not on the device.
