### ISSUE TITLE
Fuse

### ISSUE THREAD

**Issue by pmkone** [riptidewave93/UNVR-NAS#16]
Fuse modules among other things missing? Is it possible to add them? Havimg Mergerfs would make me splooge happiness

**Comment by riptidewave93** [comment]
Similar to https://github.com/riptidewave93/UNVR-NAS/issues/14 we are very limited on the modules available, but I may be able to get fuse added. Ill do some digging over the next week or two to see if this is possible.

**Comment by pmkone** [comment]
Your time would be appreciated. I understand ubiquiti hasn't been willing to release gpl kernels.

**Comment by pmkone** [comment]
I found that the same source that you used for btrfs had mentioned of fuse. Whether it would work or how to make it work is outside of my capabilities. I wouldn't even know how to begin building something out of tree or making this work   I am going to keep looking for something more recent.

**Comment by riptidewave93** [comment]
@pmkone fuse will be added to this repo shortly. :slightly_smiling_face: 
```
root@unvr-nas:/home/debian# modprobe fuse
root@unvr-nas:/home/debian# dmesg | grep fuse
[    6.943462] systemd[1]: Starting modprobe@fuse.service - Load Kernel Module fuse...
[    6.952447] fuse init (API version 7.27)
root@unvr-nas:/home/debian# lsmod | grep fuse
fuse                  110592  1
```
