### ISSUE TITLE
UNVR Shutdown

### ISSUE THREAD

**Issue by pmkone** [riptidewave93/UNVR-NAS#17]
Not to be a bother, just reporting an issue I came accross. Shutdown doesn't actually shut it down. It acts like a restart where it boots right back up again. Not sure what can be done about that as it might not be controlled by this "OS". Beyond my scope of skillset to figure out in linux without guidance. Can provide whatever you need

**Comment by riptidewave93** [comment]
@pmkone was this done via an SSH command (if so which command?) or the OMV Web IU?

**Comment by pmkone** [comment]
Both ways result the same. From ssh I have tried shutdown, poweroff (both end up booting right back up). From omv also same thing

**Comment by pmkone** [comment]
Thanks for the work with fuse. Works well so far on my limited testing as of yet. But the shutdown issue persists. Does your unvr shutdown and stay off?

**Comment by riptidewave93** [comment]
@pmkone I have yet to have time to diagnose this issue, I will get to it when I have some more free time. I know I was having issues with this early on, but fixed it atleast on the UNVR Pro by changing the touchscreen shutdown command, as seen at https://github.com/riptidewave93/UNVR-NAS/blob/54f083a1b05f891d9b219fa015870687e3482a7a/overlay/filesystem/usr/bin/ubnt-systool#L4 but that logic ONLY runs when the touch screen is used to issue a shutdown.

**Comment by pmkone** [comment]
Oddly running poweroff with halt flag worked after updating to fuse version. Shutdown still does not

**Comment by riptidewave93** [comment]
This should be fixed as of https://github.com/riptidewave93/UNVR-NAS/commit/d5f1fa0356e6aa4502772d1ec642c12242b9fa4a. I hate this solution, but it works. More reason to try and get GPL sources. ugh.

**Comment by pmkone** [comment]
Hmm. Does this thing have WOL? Could that be causing It?

**Comment by pmkone** [comment]
Actually...

I have a hunch it has something to do with missing ubnt-systool as on my stock NVR it is the same unless I use this tool in cli to shutdown

**Comment by riptidewave93** [comment]
This is not a WOL thing, it's a kernel/u-boot/device configuration. The system is set to "reset" if a normal shutdown is done, instead of a halt.
