### ISSUE TITLE
Error while trying to run MAKE

### ISSUE THREAD

**Issue by Padre653** [riptidewave93/UNVR-NAS#19]
I get the following error while I try to run the MAKE program: 
179.6 /bin/sh: 1: /setup_mkimage.sh: Permission denied
The process stops after this error. Any chance you could point me in the right direction? 
I have run the program with sudo and also under sudo -s.

[MAKE error.txt](https://github.com/user-attachments/files/17117108/MAKE.error.txt)

**Comment by riptidewave93** [comment]
@Padre653 this is a sign that the script isn't executable, which it should be if you git cloned the repo. If you downloaded a zip/tar and extracted, this kind of issue can occur. You may be able to fix this manually with:
```
chmod +x ./scripts/*.sh
chmod +x ./scripts/docker/*.sh
chmod +x ./scripts/docker/bootstrap/001-bootstrap
```

And then before you build the image you should reset your build environment with:
```make distclean```

**Comment by Padre653** [comment]
That definitely helped, thank you!!
But...
Now I get a permission error at the next step:
Finished 02_download_dependencies.sh
Starting 03_docker.sh
Setting up the toolchain for docker...
Docker: Extracting Firmware...
/repo/scripts/docker/extract_firmware.sh: line 8: /repo/scripts/ubnt-fw-parse.py: Permission denied
make: *** [Makefile:9: build] Error 126

So....
I stopped being lazy and learned how to clone the project to my server. Everything is progressing nicely now. Thank you for the help!
