### ISSUE TITLE
Early Access update possible?

### ISSUE THREAD

**Issue by DavidCarl** [riptidewave93/UNVR-NAS#20]
Hello,

I got a UNVRPro thats running version 4.1.5, and wondered if it would be possible to run UNVR-NAS on it?

It seems like build chain requires 4.0.18, but I dont have a deep enough understanding of this project to migrate it myself.

Atm. I am looking into a possible downgrade path, if there even is one :)

Sincerely
David Carl

**Comment by DavidCarl** [comment]
Got it downgraded successfully.

I SSHed into the box and executed

`ubnt-systool fwupdate https://fw-download.ubnt.com/data/unifi-nvr/13b8-UNVRPRO-4.0.18-30952e81-b1e7-47fe-9bed-bd8d963d6048.bin`

Sorry about that :)

**Comment by cainmp** [comment]
For others, I was able to use this with 4.1.5 firmware, I just had to update the config file after cloning the repo to reference the 4.1.5 file name and checksum
