### ISSUE TITLE
How to update to newer releases

### ISSUE THREAD

**Issue by olafnorge** [riptidewave93/UNVR-NAS#23]
Hi, thanks for this project. 

I installed the most recent branch to my UNVR4 w/o any hassle but I wonder what I need to do to keep up w/ your changes in the future.

If I am not mistaken if I reflash all my changes will be purged and the box will get kind of factory reset to whatever is in the repo.

**Comment by riptidewave93** [comment]
Correct, this repo is designed as a "flash and forget" so unless there's a new release fixing a bug you are dealing with, there should be no need to reflash an image generated from this repo. That was the idea when building this atleast; as trying to make an entire R/W OS in-place upgradable is not an easy task...
