### ISSUE TITLE
During rescue mode no drive can be seen, root FS errors, and missing quota on the kernel

### ISSUE THREAD

**Issue by jarossi** [riptidewave93/UNVR-NAS#24]
Hi few issues I am picking up.

When rebooted the UNVR on on rescue mode, with firmware version 0592-UNVR-4.1.9-6ea55371-e18f-4de9-a67e-a5c63bb0fc2f.bin it won't see the drive I copied the build image to, I won't be able to flash.

Gladly telnet worked, the network was up, and was able to use netcat to copy the image and flash it like that.

I am seeing some errors for the root fs, that seem to increment with reboots:

```
[  310.715328] EXT4-fs (boot2): error count since last fsck: 4
[  310.720897] EXT4-fs (boot2): initial error at time 1733355149: ext4_validate_block_bitmap:384
[  310.729418] EXT4-fs (boot2): last error at time 1733426552: ext4_validate_block_bitmap:384
[  457.332543] EXT4-fs (md0): re-mounted. Opts: user_xattr,usrquota,grpquota,acl
[  476.083620] nfsd: last server has exited, flushing export cache

```

wondering if from rescue mode we can run e2fsck on the root FS? any way to get rid of this.

Also when attempting to create/mount FS with quotas openmedia vault cannot mount the FS:

`The kernel was not built with CONFIG_QUOTA and CONFIG_QFMT_V2`

Wondering if this can be patched on the built kernel to include those settings.

BTW, the current kernel includes /proc/config.gz, would it possible to use this config to built a more recent kernel?

Regards

Juan.-

**Comment by riptidewave93** [comment]
sounds like this is multiple issues, ill start with the kernel question; without GPL from Unifi we can not build an entire kernel from scratch; the best I can do is port in modules from their now 2~ year old GPL drop and hope they work. (this all depends on what changes have occurred in their kernel source since then, which we don't know due to lack of recent GPL) Ill take a peek but no promises.

As for your e2fsck errors, it's possible the latest recovery may have changes to how it handles mounts. Specifically, can you see if any /dev/boot partitions are mounted when you boot into recovery? If so, you will want to UNMOUNT these partitions before you do the dd command that writes OMV to the UNVR.

**Comment by riptidewave93** [comment]
@jarossi here's a PR/branch you can test that hopefully adds quota support :) 

https://github.com/riptidewave93/UNVR-NAS/pull/25

**Comment by jarossi** [comment]
@riptidewave93 excellent!. 

BTW got rid of the root fs errors by rebooting in rescue mode and using e2fsck on /dev/boot2.

Also another thing I picking up is that the SFP port did not work for me with a DAC cable at all. Is this expected?

Regards

Juan.-

**Comment by riptidewave93** [comment]
@jarossi please test that PR if you can and let me know if it resolves the quota issue, if so ill merge it.

As for your SFP issue, I have not had issues using DAC cables or my SFP to 10GB RJ45 adapter. Can you try other cables or adapters? Is this issue just in recovery, or also in the actual OMV image you flashed?

**Comment by jarossi** [comment]
I will try the PR today, sorry for the delay.  I have tried several DACs, not sure what the issue may be.

Regards

Juan.-

**Comment by jarossi** [comment]
@riptidewave93 I have tested the module and loads fine.

```
ladmin@unvr-nas:~$ lsmod
Module                  Size  Used by
quota_v2               16384  0
quota_tree             20480  1 quota_v2
btrfs                1077248  0
```

loads fine, but the kernel still complains about not having that built in.

 I tried to replace the uImage in /boot without reflashing (remount in RW, replace file), but I think it may not picking it up:


```
ladmin@unvr-nas:~$ zgrep -i quota /proc/config.gz
CONFIG_QUOTA=y
# CONFIG_QUOTA_NETLINK_INTERFACE is not set
# CONFIG_PRINT_QUOTA_WARNING is not set
# CONFIG_QUOTA_DEBUG is not set
CONFIG_QUOTACTL=y
```

Is there a way, or another process to replace the kernel to be loaded without reflashing everything? My system is about to go into semi production

Regards

Juan.-

**Comment by riptidewave93** [comment]
Hey Juan, thanks for testing. Sadly if the module itself isn't enough then there's nothing I can do to support this without GPL kernel source from Unifi.

**Comment by jarossi** [comment]
cool, I reflashed, but getting the same effect.

I guess you will have to place some notes about OMV not be able to use quotas when creating and mounting FS.
