### ISSUE TITLE
Add Unifi-drive package

### ISSUE THREAD

**Issue by christophermichaelshaw** [riptidewave93/UNVR-NAS#26]
Would it be possible to have the Unifi-drive package compiled into the firmware? Now that Btrfs kernel module is working, we should be able to get the Unifi-drive integration running (albeit with manual Btrfs volume creation).

**Comment by riptidewave93** [comment]
unifi-drive is not something that would work with this repo, as the purpose of this repo is for openmediavault on the UNVRs and not Unifi's own unifi-drive package. I may look at seeing if I can get unifi-drive to work in docker, like I did with [Unifi Protect in the past](https://github.com/riptidewave93/unifi-protect-arm64), but it is not high on my priority list.

**Comment by TaimurAyaz** [comment]
@christophermichaelshaw https://github.com/TaimurAyaz/unifi-unvr-to-unas
