### ISSUE TITLE
Add support for UNVR

### ISSUE THREAD

**Issue by riptidewave93** [riptidewave93/UNVR-NAS#7]
To really make this repo awesome, we should also support the 1U UNVR. Currently I am attempting to get a second hand one for cheap, but if anyone wants to donate one feel free to reach out to me. :)

chrisrblake93@gmail.com

**Comment by riptidewave93** [comment]
I have a UNVR enroute, and working branch will be at https://github.com/riptidewave93/UNVR-NAS/tree/riptide/unvr-support until I can get it stable.

**Comment by tangelogh** [comment]
Hi, I have a donated UNVR that I would love to use.
There was an older project called urnvr but it required a specific older firmware version and I wasn't able to downgrade my UNVR to that firmware.

I can help you test things out.

**Comment by riptidewave93** [comment]
> I can help you test things out.

I have one enroute so that may not be necessary until I have the branch more mature, but in the mean time if you could send me the output of the following commands id appreciate it. :) Feel free to strip out the SN/Mac addresses from the output.

```
cat /proc/cmdline
cat /proc/mtd
cat /proc/ubnthal/board
cat /proc/ubnthal/system.info
fdisk -l /dev/boot
```

**Comment by riptidewave93** [comment]
PR up at https://github.com/riptidewave93/UNVR-NAS/pull/11

**Comment by riptidewave93** [comment]
Merged in #11 which should do the magic, but I need to test once my UNVR shows up in the next 4~ or so days. It's untested, but "should" work but I recommend waiting for me to test/update the README.md to mark it as tested.

**Comment by tangelogh** [comment]
Sorry for the delay, didn't get a notification.

```
cat /proc/cmdline
pci=pcie_bus_perf console=ttyS0,115200 sysid=ea16 boot_carrier= root= reboot=warm
```

```
cat /proc/mtd
dev:    size   erasesize  name
mtd0: 001c0000 00001000 "u-boot"
mtd1: 00010000 00001000 "u-boot env"
mtd2: 00010000 00001000 "u-boot env redundant"
mtd3: 00010000 00001000 "Factory"
mtd4: 00010000 00001000 "EEPROM"
mtd5: 01000000 00001000 "recovery kernel"
mtd6: 00e00000 00001000 "config"
mtd7: 00200000 00040000 "al_boot"
mtd8: 00100000 00040000 "device_tree"
mtd9: 01000000 00040000 "linux_kernel"
mtd10: 3ed00000 00040000 "rootfs"
```

```
cat /proc/ubnthal/board
format=0002
version=0001
boardid=ea16
vendorid=0777
bomrev=000b101d
hwaddrbbase=74:ac:b9:4d:XX:XX
EthMACAddrCount=2
WiFiMACAddrCount=0
BtMACAddrCount=255
regdmn[0]=0000
regdmn[1]=ffff
regdmn[2]=ffff
regdmn[3]=ffff
regdmn[4]=ffff
regdmn[5]=ffff
regdmn[6]=ffff
regdmn[7]=ffff
```

```
cat /proc/ubnthal/system.info
cpu=AL324V2
cpuid=411ed073
flashSize=33554432
ramsize=4294967296
vendorid=0777
systemid=ea16
shortname=UNVR4
boardrevision=29
serialno=74acb9XXXXXX
manufid=0004
mfgweek=202024
qrid=Vi9o3x
eth0.macaddr=74:ac:b9:4d:XX:XX
eth1.macaddr=74:ac:b9:4d:XX:XX
device.hashid=74cda571f97d1650
device.anonid=41eeed96-dab7-4777-84cd-a571f97d1650
regdmn[]=0000ffffffffffffffffffffffffffff
cpu_rev_id=00010000
```

```
fdisk -l /dev/boot
fdisk: cannot open /dev/boot: No such file or directory
```

This last one may be because mine is the older model that uses a USB pen drive instead of eMMC?

**Comment by riptidewave93** [comment]
Hello @tangelogh, thank you for the output. You are correct that you have the older model that uses a USB drive which is why /dev/boot doesn't exist on your device. However, the good news is this firmware "should" still work on that model, as long as u-boot plays nice (which it should).
